### ISSUE TITLE
Nowhere to define user and pass

### ISSUE THREAD

**Issue by sugarat333** [cenk1cenk2/docker-softether-vpncli#5]
Hi there. I am trying to use this container to connect to a SoftEther server.  I do not see anywhere to define the username and password that is defined on the server.  I have directed it to the .vpn file, but how will it connect when I have not defined a username and password anywhere?  Please clarify what environment variable would allow setting of username and password. Thanks

**Comment by cenk1cenk2** [comment]
There is no way to define it with environment variables unfortunetly. When you export the vpn file from gui from the client it ask you should i keep the username and password. The way i do is it like that and there is currently no easier way around it. I may try to generate a vpn file but idk if it is required. 

Wish you a plesant weekend. I will check out if i can do it with env variables as well later on.

**Comment by sugarat333** [comment]
Okay no problem.  I have managed to connect to softether server using container mitsutake/softether-vpnclient but I thank you for the fast response. Wishing you a good weekend also.
